### ISSUE TITLE
Cannot build a project with autohelp included. 

### ISSUE THREAD

**Issue by blt** [stolen/autohelp#3]
I'd like to make use of autohelp in a large project. Builds crash with `{undef, [{autohelp,parse_transform,...`; I've isolated this problem in a smaller project [here](https://github.com/blt/parse_fight).

**Comment by stolen** [comment]
I've took a look on your project.
Currently build crashes because you have specified `{parse_transform, autohelp}` as your global compile option. Rebar builds dependencies with it and cannot compile anything because autohelp is dependency itself.
Obviously it is the way autohelp should be used. Will read `rebar` documentation and source to figure out way to override compile options.

**Comment by stolen** [comment]
OK, seems to be fixed. Please bump autohelp revision in your `rebar.config`.

**Comment by blt** [comment]
Builds just fine; thank you.
